add_rules("mode.debug", "mode.release")
set_languages("cxx20")
set_project("poker-cli")
add_requires("boost", {configs = {asio = true}})

target("server")
    set_kind("binary")
    add_files("src/server.cpp")
    add_includedirs("include")
    add_packages("boost")

target("client")
    set_kind("binary")
    add_files("src/main.cpp", "src/client.cpp", "src/deck.cpp", "src/game.cpp", "src/chip.cpp")
    add_includedirs("include")
    add_packages("boost")